#!/bin/sh
#
# @name Generic Iris Quadrotor SITL
#
# @type Quadrotor Wide
#

. ${R}etc/init.d/rc.fw_defaults


param set-default RWTO_TKOFF 1

param set-default SENS_EN_ARSPDSIM 0

param set-default FW_USE_AIRSPD 0
param set-default SYS_HAS_NUM_ASPD 0

param set-default FW_LND_ANG 8

# param set-default NPFG_PERIOD 12

# param set-default FW_PR_P 0.9
# param set-default FW_PR_FF 0.2
# param set-default FW_PR_I 0.5
# param set-default TRIM_PITCH -0.15

# param set-default FW_RR_FF 0.5
# param set-default FW_RR_P 0.4
# param set-default FW_RR_I 0.7

# param set-default FW_R_RMAX 56.15

# param set-default FW_YR_FF 0.3
# param set-default FW_YR_P 1.3
# param set-default FW_YR_I 0.7

# #param set-default FW_PSP_OFF 0
# param set-default FW_P_LIM_MIN -15

param set-default FW_T_CLMB_MAX 20.0
param set-default FW_TKO_PITCH_MIN 20
param set-default FW_T_SINK_MAX 3.5
param set-default FW_T_SINK_MIN 3

# param set-default FW_AIRSPD_MIN 20.0
# param set-default FW_THR_ASPD_MIN 0.5
# param set-default FW_THR_TRIM 0.5
# param set-default FW_THR_IDLE 0.5


param set-default FW_W_EN 1

param set-default MIS_TAKEOFF_ALT 50

param set-default NAV_ACC_RAD 15
param set-default NAV_DLL_ACT 2

param set-default CA_AIRFRAME 1

param set-default COM_PREARM_MODE 2

param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_PX -0.3



param set-default CA_SV_CS_COUNT 2

param set-default CA_SV_CS0_TYPE	5
param set-default CA_SV_CS0_TRQ_R  -0.5
param set-default CA_SV_CS0_TRQ_Y	0.0
param set-default CA_SV_CS0_TRQ_P	0.3


param set-default CA_SV_CS1_TYPE    6
param set-default CA_SV_CS1_TRQ_R   0.5
param set-default CA_SV_CS1_TRQ_Y	0.0	
param set-default CA_SV_CS1_TRQ_P	0.3




# elevator, aileron, rudder, throttle
param set-default PWM_MAIN_FUNC1 101 # motor
param set-default PWM_MAIN_FUNC2 201 # elevator
param set-default PWM_MAIN_FUNC3 202 # left aileron



# param set-default CA_SV_CS_COUNT 4

# param set-default CA_SV_CS0_TRQ_R -0.5
# param set-default CA_SV_CS0_TYPE 1

# param set-default CA_SV_CS1_TRQ_R 0.5
# param set-default CA_SV_CS1_TYPE 2

# param set-default CA_SV_CS2_TRQ_P 1
# param set-default CA_SV_CS2_TYPE 3

# param set-default CA_SV_CS3_TRQ_Y 1
# param set-default CA_SV_CS3_TYPE 4


# # elevator, aileron, rudder, throttle
# param set-default PWM_MAIN_FUNC1 101 # motor

# param set-default PWM_MAIN_FUNC2 203 # elevator
# param set-default PWM_MAIN_FUNC3 201 # left aileron
# param set-default PWM_MAIN_FUNC4 202 # right aileron
# param set-default PWM_MAIN_FUNC5 204 # rudder